name: release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: release
          ref: release
      - uses: actions/checkout@v2
        with:
          path: master
          ref: master
      - run: |
          cd master
          stopMarker=$(uuidgen)
          echo "::stop-commands::$stopMarker"
          msg=$(git log -1 --pretty=%B)
          echo "::set-env name=MSG::$msg"
          echo "::$stopMarker::"

      - run: |
          export NODE_OPTIONS=--openssl-legacy-provider 
          cd master
          yarn
          yarn webpack
      - run: >
          cp master/dist/bundle.js release/index.js && cp master/action.yml release/action.yml
      - uses: EndBug/add-and-commit@v4
        with:
          add: '.'
          message: '${{env.MSG}}'
          cwd: './release'
          ref: 'release'
          signoff: true
        env:
          GITHUB_TOKEN: '{ { secrets.GITHUB_TOKEN } }'
